version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    groups:
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
    schedule:
      interval: "monthly"
